project_id = "yibszncvwmefwamayfty"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.outlook-oauth]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.google-calendar-oauth]
verify_jwt = false
