import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  FileText, Share2, ChevronLeft, ChevronRight, 
  Brain, Shield, Target, AlertTriangle, Heart,
  TrendingUp, Network, Sparkles, Download
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { shareContent } from '@/lib/nativeFeatures';
import { motion, AnimatePresence } from 'framer-motion';

interface MobileIntelligenceReportProps {
  profileId: string;
  profileName: string;
  onClose?: () => void;
}

const REPORT_SECTIONS = [
  { id: 'summary', label: 'Summary', icon: FileText },
  { id: 'personality', label: 'Personality', icon: Brain },
  { id: 'trust', label: 'Trust', icon: Shield },
  { id: 'influence', label: 'Influence', icon: Target },
  { id: 'preferences', label: 'Preferences', icon: Sparkles },
  { id: 'network', label: 'Network', icon: Network },
  { id: 'relationship', label: 'Relationship', icon: Heart },
  { id: 'risks', label: 'Risks', icon: AlertTriangle },
];

export function MobileIntelligenceReport({
  profileId,
  profileName,
  onClose,
}: MobileIntelligenceReportProps) {
  const [currentSection, setCurrentSection] = useState(0);
  const [activeTab, setActiveTab] = useState('cards');

  // Fetch all intelligence data
  const { data: reportData, isLoading } = useQuery({
    queryKey: ['mobile-intelligence-report', profileId],
    queryFn: async () => {
      const [
        psychProfile,
        trustData,
        influenceProfile,
        preferences,
        relationshipScore,
        predictions,
      ] = await Promise.all([
        supabase
          .from('ai_analyses')
          .select('result')
          .eq('profile_id', profileId)
          .eq('analysis_type', 'psychological')
          .order('generated_at', { ascending: false })
          .limit(1)
          .maybeSingle(),
        supabase
          .from('trust_assessments')
          .select('*')
          .eq('profile_id', profileId)
          .order('assessed_at', { ascending: false })
          .limit(1)
          .maybeSingle(),
        supabase
          .from('contact_influence_profiles')
          .select('*')
          .eq('profile_id', profileId)
          .maybeSingle(),
        supabase
          .from('contact_predicted_preferences')
          .select('*')
          .eq('profile_id', profileId)
          .order('confidence_score', { ascending: false }),
        supabase
          .from('relationship_scores')
          .select('*')
          .eq('profile_id', profileId)
          .order('calculated_at', { ascending: false })
          .limit(1)
          .maybeSingle(),
        supabase
          .from('behavioral_predictions')
          .select('*')
          .eq('profile_id', profileId)
          .order('created_at', { ascending: false })
          .limit(5),
      ]);

      return {
        psychological: psychProfile.data?.result as any,
        trust: trustData.data,
        influence: influenceProfile.data,
        preferences: preferences.data || [],
        relationship: relationshipScore.data,
        predictions: predictions.data || [],
      };
    },
    enabled: !!profileId,
  });

  const handleShare = async () => {
    const summary = `Intelligence Report: ${profileName}\n\nGenerated by AI Intelligence System`;
    await shareContent({
      title: `Intelligence Report: ${profileName}`,
      text: summary,
    });
  };

  const goToSection = (direction: 'prev' | 'next') => {
    if (direction === 'prev' && currentSection > 0) {
      setCurrentSection(currentSection - 1);
    } else if (direction === 'next' && currentSection < REPORT_SECTIONS.length - 1) {
      setCurrentSection(currentSection + 1);
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background p-4 space-y-4">
        <Skeleton className="h-12 w-full" />
        <Skeleton className="h-64 w-full" />
        <Skeleton className="h-32 w-full" />
      </div>
    );
  }

  const section = REPORT_SECTIONS[currentSection];
  const SectionIcon = section.icon;

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-background/95 backdrop-blur border-b px-4 py-3 safe-top">
        <div className="flex items-center justify-between">
          <Button variant="ghost" size="icon" onClick={onClose}>
            <ChevronLeft className="h-5 w-5" />
          </Button>
          <div className="text-center">
            <h1 className="font-semibold text-sm truncate max-w-[200px]">
              {profileName}
            </h1>
            <p className="text-xs text-muted-foreground">Intelligence Report</p>
          </div>
          <Button variant="ghost" size="icon" onClick={handleShare}>
            <Share2 className="h-5 w-5" />
          </Button>
        </div>

        {/* View Toggle */}
        <div className="mt-3">
          <Tabs value={activeTab} onValueChange={setActiveTab}>
            <TabsList className="w-full">
              <TabsTrigger value="cards" className="flex-1">Cards</TabsTrigger>
              <TabsTrigger value="list" className="flex-1">List</TabsTrigger>
            </TabsList>
          </Tabs>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-hidden">
        {activeTab === 'cards' ? (
          /* Card View - Swipeable */
          <div className="h-full flex flex-col">
            {/* Section Progress */}
            <div className="px-4 py-2 flex items-center gap-2">
              {REPORT_SECTIONS.map((s, i) => (
                <div
                  key={s.id}
                  className={cn(
                    "h-1 flex-1 rounded-full transition-colors",
                    i <= currentSection ? "bg-primary" : "bg-muted"
                  )}
                  onClick={() => setCurrentSection(i)}
                />
              ))}
            </div>

            {/* Current Section Card */}
            <div className="flex-1 px-4 py-2">
              <AnimatePresence mode="wait">
                <motion.div
                  key={section.id}
                  initial={{ opacity: 0, x: 50 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -50 }}
                  className="h-full"
                >
                  <Card className="h-full flex flex-col">
                    <CardHeader className="pb-2">
                      <CardTitle className="flex items-center gap-2 text-lg">
                        <SectionIcon className="h-5 w-5 text-primary" />
                        {section.label}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="flex-1 overflow-auto">
                      <ReportSectionContent
                        sectionId={section.id}
                        data={reportData}
                        profileName={profileName}
                      />
                    </CardContent>
                  </Card>
                </motion.div>
              </AnimatePresence>
            </div>

            {/* Navigation */}
            <div className="px-4 py-3 flex items-center justify-between safe-bottom">
              <Button
                variant="outline"
                size="sm"
                onClick={() => goToSection('prev')}
                disabled={currentSection === 0}
              >
                <ChevronLeft className="h-4 w-4 mr-1" />
                Previous
              </Button>
              <span className="text-sm text-muted-foreground">
                {currentSection + 1} / {REPORT_SECTIONS.length}
              </span>
              <Button
                size="sm"
                onClick={() => goToSection('next')}
                disabled={currentSection === REPORT_SECTIONS.length - 1}
              >
                Next
                <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </div>
          </div>
        ) : (
          /* List View */
          <ScrollArea className="h-full">
            <div className="p-4 space-y-4 safe-bottom">
              {REPORT_SECTIONS.map((s) => {
                const Icon = s.icon;
                return (
                  <Card key={s.id}>
                    <CardHeader className="pb-2">
                      <CardTitle className="flex items-center gap-2 text-base">
                        <Icon className="h-4 w-4 text-primary" />
                        {s.label}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <ReportSectionContent
                        sectionId={s.id}
                        data={reportData}
                        profileName={profileName}
                        compact
                      />
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </ScrollArea>
        )}
      </div>
    </div>
  );
}

interface ReportSectionContentProps {
  sectionId: string;
  data: any;
  profileName: string;
  compact?: boolean;
}

function ReportSectionContent({ sectionId, data, profileName, compact }: ReportSectionContentProps) {
  if (!data) {
    return <p className="text-muted-foreground text-sm">No data available</p>;
  }

  switch (sectionId) {
    case 'summary':
      return (
        <div className="space-y-3">
          <p className="text-sm">
            Comprehensive intelligence profile for <strong>{profileName}</strong>.
          </p>
          <div className="grid grid-cols-2 gap-3">
            <StatCard label="Trust Score" value={data.trust?.overall_trust_score || 0} />
            <StatCard label="Relationship" value={data.relationship?.overall_score || 0} />
            <StatCard label="Preferences" value={data.preferences?.length || 0} suffix=" found" />
            <StatCard label="Predictions" value={data.predictions?.length || 0} suffix=" active" />
          </div>
        </div>
      );

    case 'personality': {
      const psych = data.psychological;
      if (!psych) return <p className="text-muted-foreground text-sm">Run psychological analysis to populate</p>;
      return (
        <div className="space-y-3">
          {psych.personality_type && (
            <Badge variant="outline" className="text-sm">{psych.personality_type}</Badge>
          )}
          {psych.key_traits?.slice(0, compact ? 3 : 6).map((trait: string, i: number) => (
            <Badge key={i} variant="secondary" className="mr-1 mb-1">{trait}</Badge>
          ))}
          {psych.summary && (
            <p className="text-sm text-muted-foreground">{psych.summary}</p>
          )}
        </div>
      );
    }

    case 'trust': {
      const trust = data.trust;
      if (!trust) return <p className="text-muted-foreground text-sm">No trust assessment available</p>;
      return (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm">Overall Trust</span>
            <span className="font-mono font-bold">{trust.overall_trust_score}%</span>
          </div>
          <Progress value={trust.overall_trust_score} />
          {!compact && (
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div>Reliability: {trust.reliability_score || 0}%</div>
              <div>Consistency: {trust.consistency_score || 0}%</div>
              <div>Transparency: {trust.transparency_score || 0}%</div>
              <div>Competence: {trust.competence_score || 0}%</div>
            </div>
          )}
        </div>
      );
    }

    case 'influence': {
      const influence = data.influence;
      if (!influence) return <p className="text-muted-foreground text-sm">No influence profile available</p>;
      return (
        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div className="flex justify-between">
              <span>Authority</span>
              <span>{influence.authority_susceptibility || 0}%</span>
            </div>
            <div className="flex justify-between">
              <span>Social Proof</span>
              <span>{influence.social_proof_susceptibility || 0}%</span>
            </div>
            <div className="flex justify-between">
              <span>Liking</span>
              <span>{influence.liking_susceptibility || 0}%</span>
            </div>
            <div className="flex justify-between">
              <span>Scarcity</span>
              <span>{influence.scarcity_susceptibility || 0}%</span>
            </div>
          </div>
        </div>
      );
    }

    case 'preferences': {
      const prefs = data.preferences?.slice(0, compact ? 4 : 10);
      if (!prefs?.length) return <p className="text-muted-foreground text-sm">No preferences predicted yet</p>;
      return (
        <div className="space-y-2">
          {prefs.map((p: any) => (
            <div key={p.id} className="flex items-start justify-between gap-2 text-sm">
              <div className="flex-1 min-w-0">
                <div className="font-medium truncate">{p.preference_key}</div>
                <div className="text-xs text-muted-foreground truncate">{p.predicted_value}</div>
              </div>
              <Badge variant="outline" className="text-xs flex-shrink-0">
                {Math.round(p.confidence_score * 100)}%
              </Badge>
            </div>
          ))}
        </div>
      );
    }

    case 'network':
      return (
        <p className="text-muted-foreground text-sm">
          Network analysis visualizes connections and influence paths.
          View in desktop for full graph visualization.
        </p>
      );

    case 'relationship': {
      const rel = data.relationship;
      if (!rel) return <p className="text-muted-foreground text-sm">No relationship score available</p>;
      return (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm">Overall Score</span>
            <span className="font-mono font-bold">{rel.overall_score}%</span>
          </div>
          <Progress value={rel.overall_score} />
          <Badge variant={rel.trend === 'up' ? 'default' : rel.trend === 'down' ? 'destructive' : 'secondary'}>
            <TrendingUp className={cn("h-3 w-3 mr-1", rel.trend === 'down' && "rotate-180")} />
            {rel.trend || 'Stable'}
          </Badge>
        </div>
      );
    }

    case 'risks': {
      const preds = data.predictions?.filter((p: any) => p.prediction_type === 'churn' || p.prediction_type === 'risk');
      if (!preds?.length) return <p className="text-muted-foreground text-sm">No risk predictions available</p>;
      return (
        <div className="space-y-2">
          {preds.slice(0, compact ? 2 : 5).map((p: any) => (
            <div key={p.id} className="p-2 bg-destructive/10 rounded-lg">
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">{p.prediction_type}</span>
                <Badge variant="destructive" className="text-xs">
                  {Math.round((p.confidence_score || 0) * 100)}%
                </Badge>
              </div>
            </div>
          ))}
        </div>
      );
    }

    default:
      return null;
  }
}

function StatCard({ label, value, suffix = '%' }: { label: string; value: number; suffix?: string }) {
  return (
    <div className="bg-muted/50 rounded-lg p-3 text-center">
      <div className="text-2xl font-bold">{value}{suffix}</div>
      <div className="text-xs text-muted-foreground">{label}</div>
    </div>
  );
}
