REVOKE EXECUTE ON FUNCTION public.log_budget_change() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refresh_contact_storage_stats() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.refresh_contact_storage_stats() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.search_document_embeddings(p_user_id uuid, p_profile_id uuid, p_source_type text, p_limit integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.search_document_embeddings(p_user_id uuid, p_profile_id uuid, p_source_type text, p_limit integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_contact_media_counts(p_user_id uuid, p_profile_id uuid, p_skip_analyzed boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_media_counts(p_user_id uuid, p_profile_id uuid, p_skip_analyzed boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.delete_api_key(p_name text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_api_key(p_name text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_document_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_api_key(p_name text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_api_key(p_name text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_contact_media_paginated(p_user_id uuid, p_profile_id uuid, p_media_type text, p_search_query text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_media_paginated(p_user_id uuid, p_profile_id uuid, p_media_type text, p_search_query text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_media_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.increment_automation_counters(p_rule_id uuid, p_field text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_automation_counters(p_rule_id uuid, p_field text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_stale_bulk_items(p_user_id uuid, p_days_old integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cleanup_stale_bulk_items(p_user_id uuid, p_days_old integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.archive_old_messages(days_old integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.archive_old_messages(days_old integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_user_clearance(_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_user_clearance(_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.owns_profile(profile_uuid uuid, uid uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.owns_profile(profile_uuid uuid, uid uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.clean_expired_cache() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.clean_expired_cache() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.queue_observation_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.bulk_update_thread_counts(thread_updates jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.bulk_update_thread_counts(thread_updates jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_contact_filter_options(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_filter_options(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_media_ids_for_analysis(p_user_id uuid, p_profile_id uuid, p_media_types text[], p_skip_analyzed boolean, p_limit integer, p_offset integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_media_ids_for_analysis(p_user_id uuid, p_profile_id uuid, p_media_types text[], p_skip_analyzed boolean, p_limit integer, p_offset integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_contact_method_access(p_contact_method_id uuid, p_access_type text, p_was_decrypted boolean, p_access_context text, p_ip_address inet) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_contact_method_access(p_contact_method_id uuid, p_access_type text, p_was_decrypted boolean, p_access_context text, p_ip_address inet) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_unread_alerts_count(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_unread_alerts_count(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.trigger_auto_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.trigger_surveillance_alert_on_anomaly() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_document_folders(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_document_folders(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_storage_stats_refresh() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.queue_message_for_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.queue_media_for_analysis() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.match_documents(p_user_id uuid, p_query_embedding extensions.vector, p_match_threshold double precision, p_match_count integer, p_profile_id uuid, p_source_types text[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.match_documents(p_user_id uuid, p_query_embedding extensions.vector, p_match_threshold double precision, p_match_count integer, p_profile_id uuid, p_source_types text[]) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.queue_semantic_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_bulk_session_stats() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_entity_mentions_cross_contact(p_user_id uuid, p_entity_name text, p_entity_type text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_entity_mentions_cross_contact(p_user_id uuid, p_entity_name text, p_entity_type text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_communication_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_message_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_single_contact_storage(p_user_id uuid, p_profile_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_single_contact_storage(p_user_id uuid, p_profile_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_storage_summary(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_storage_summary(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_relationship_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_clearance(_user_id uuid, _required clearance_level) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_clearance(_user_id uuid, _required clearance_level) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.update_intelligence_session_progress() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_counts(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_counts(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_analysis_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_storage_stats(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_storage_stats(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_bulk_session_progress(p_session_id uuid, p_cost_cents integer, p_is_completed boolean, p_is_failed boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_bulk_session_progress(p_session_id uuid, p_cost_cents integer, p_is_completed boolean, p_is_failed boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_event_activity() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_role() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.find_cross_reference_matches(p_user_id uuid, p_reference_type text, p_normalized_value text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.find_cross_reference_matches(p_user_id uuid, p_reference_type text, p_normalized_value text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.check_bulk_session_completion() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_storage_snapshot(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_storage_snapshot(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.bootstrap_first_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.bootstrap_first_admin() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_or_set_cache(p_user_id uuid, p_cache_key text, p_ttl_seconds integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_or_set_cache(p_user_id uuid, p_cache_key text, p_ttl_seconds integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_psychological_profile_access() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.has_compartment(_user_id uuid, _compartment text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_compartment(_user_id uuid, _compartment text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.verify_churn_prediction_outcomes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.verify_churn_prediction_outcomes() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.check_api_keys(p_names text[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_api_keys(p_names text[]) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.compute_contact_method_access_hash() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.search_messages_v2(p_user_id uuid, p_conversation_id uuid, p_profile_id uuid, p_search_query text, p_limit integer, p_cursor_time timestamp with time zone) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.search_messages_v2(p_user_id uuid, p_conversation_id uuid, p_profile_id uuid, p_search_query text, p_limit integer, p_cursor_time timestamp with time zone) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.count_duplicate_profiles(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.count_duplicate_profiles(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.queue_message_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_media_folders(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_media_folders(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.queue_document_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.queue_media_enrichment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.check_workspace_membership(ws_id uuid, uid uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.check_workspace_membership(ws_id uuid, uid uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.track_navigation_access(p_route text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.track_navigation_access(p_route text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_contact_letter_counts(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contact_letter_counts(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.compute_email_access_hash() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_email_access(p_email_message_id uuid, p_email_thread_id uuid, p_access_type text, p_accessed_fields text[], p_was_decrypted boolean, p_clearance_used text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_email_access(p_email_message_id uuid, p_email_thread_id uuid, p_access_type text, p_accessed_fields text[], p_was_decrypted boolean, p_clearance_used text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.store_api_key(p_name text, p_value text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.store_api_key(p_name text, p_value text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.queue_media_analysis() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_prompt_version_metrics() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.match_documents_v2(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid, p_profile_id uuid, p_source_types text[], p_date_from timestamp with time zone, p_date_to timestamp with time zone) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.match_documents_v2(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid, p_profile_id uuid, p_source_types text[], p_date_from timestamp with time zone, p_date_to timestamp with time zone) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.keyword_search_documents(search_query text, p_user_id uuid, p_profile_id uuid, p_source_types text[], match_count integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.keyword_search_documents(search_query text, p_user_id uuid, p_profile_id uuid, p_source_types text[], match_count integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.compute_profile_access_hash() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_profile_access(p_profile_id uuid, p_access_type text, p_fields_accessed text[], p_was_decrypted boolean, p_access_context text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_profile_access(p_profile_id uuid, p_access_type text, p_fields_accessed text[], p_was_decrypted boolean, p_access_context text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.find_connection_path(p_user_id uuid, p_source_id uuid, p_target_id uuid, p_max_depth integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.find_connection_path(p_user_id uuid, p_source_id uuid, p_target_id uuid, p_max_depth integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_shared_organizations(p_user_id uuid, p_profile_ids uuid[]) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_shared_organizations(p_user_id uuid, p_profile_ids uuid[]) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.match_facial_embeddings(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.match_facial_embeddings(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.compute_psych_profile_access_hash() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_workspace_admin(ws_id uuid, uid uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_workspace_admin(ws_id uuid, uid uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.toggle_contact_active_status(p_profile_id uuid, p_is_active boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.toggle_contact_active_status(p_profile_id uuid, p_is_active boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_account_storage_summary(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_account_storage_summary(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_voice_session_progress(p_session_id uuid, p_is_completed boolean, p_is_failed boolean, p_is_skipped boolean, p_cost_cents integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.increment_voice_session_progress(p_session_id uuid, p_is_completed boolean, p_is_failed boolean, p_is_skipped boolean, p_cost_cents integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_contacts_for_selection(p_user_id uuid, p_search_query text, p_recent_ids uuid[], p_limit integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_contacts_for_selection(p_user_id uuid, p_search_query text, p_recent_ids uuid[], p_limit integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.activate_contact_on_interaction() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.verify_audit_chain_segment(p_user_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.verify_audit_chain_segment(p_user_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.log_security_event(p_event_type text, p_severity text, p_resource_type text, p_resource_id uuid, p_action_taken text, p_action_successful boolean, p_metadata jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.log_security_event(p_event_type text, p_severity text, p_resource_type text, p_resource_id uuid, p_action_taken text, p_action_successful boolean, p_metadata jsonb) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.batch_merge_duplicates(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.batch_merge_duplicates(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.claim_pending_tasks(p_session_id uuid, p_limit integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_pending_tasks(p_session_id uuid, p_limit integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.relink_email_threads_to_profiles(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.relink_email_threads_to_profiles(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.find_duplicate_profile(p_user_id uuid, p_first_name text, p_last_name text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.find_duplicate_profile(p_user_id uuid, p_first_name text, p_last_name text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.populate_cross_references() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_database_health_metrics(p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_database_health_metrics(p_user_id uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.search_contacts_v5(p_user_id uuid, p_search_query text, p_relationship_type text, p_relationship_subtype text, p_tag text, p_is_favorite boolean, p_is_active boolean, p_first_letter text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.search_contacts_v5(p_user_id uuid, p_search_query text, p_relationship_type text, p_relationship_subtype text, p_tag text, p_is_favorite boolean, p_is_active boolean, p_first_letter text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.merge_duplicate_profiles(p_primary_id uuid, p_duplicate_id uuid, p_user_id uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.merge_duplicate_profiles(p_primary_id uuid, p_duplicate_id uuid, p_user_id uuid) TO authenticated;