-- Phase 1: Security hardening (HPICS audit May 2026)
-- 1. Fix mutable search_path
ALTER FUNCTION public.update_updated_at_column() SET search_path = public;

-- 2. Revoke EXECUTE from anon on all SECURITY DEFINER functions
REVOKE EXECUTE ON FUNCTION public.refresh_contact_storage_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM anon;
REVOKE EXECUTE ON FUNCTION public.search_document_embeddings(p_user_id uuid, p_profile_id uuid, p_source_type text, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.delete_api_key(p_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_document_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_user_clearance(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.owns_profile(profile_uuid uuid, uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.clean_expired_cache() FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_observation_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.bulk_update_thread_counts(thread_updates jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_document_folders(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.notify_storage_stats_refresh() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_entity_mentions_cross_contact(p_user_id uuid, p_entity_name text, p_entity_type text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_relationship_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_clearance(_user_id uuid, _required clearance_level) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_intelligence_session_progress() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_counts(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_communication_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_message_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_single_contact_storage(p_user_id uuid, p_profile_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_storage_summary(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_analysis_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_storage_stats(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_bulk_session_progress(p_session_id uuid, p_cost_cents integer, p_is_completed boolean, p_is_failed boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_event_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.has_compartment(_user_id uuid, _compartment text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user_role() FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_cross_reference_matches(p_user_id uuid, p_reference_type text, p_normalized_value text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.create_storage_snapshot(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.bootstrap_first_admin() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_or_set_cache(p_user_id uuid, p_cache_key text, p_ttl_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_psychological_profile_access() FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_message_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_media_folders(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_document_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_budget_change() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_media_counts(p_user_id uuid, p_profile_id uuid, p_skip_analyzed boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_media_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_workspace_membership(ws_id uuid, uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.track_navigation_access(p_route text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_letter_counts(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.compute_email_access_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_email_access(p_email_message_id uuid, p_email_thread_id uuid, p_access_type text, p_accessed_fields text[], p_was_decrypted boolean, p_clearance_used text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.store_api_key(p_name text, p_value text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_media_analysis() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_api_key(p_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_api_keys(p_names text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.verify_churn_prediction_outcomes() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_media_paginated(p_user_id uuid, p_profile_id uuid, p_media_type text, p_search_query text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_media_activity() FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_automation_counters(p_rule_id uuid, p_field text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.compute_contact_method_access_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.search_messages_v2(p_user_id uuid, p_conversation_id uuid, p_profile_id uuid, p_search_query text, p_limit integer, p_cursor_time timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.count_duplicate_profiles(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_stale_bulk_items(p_user_id uuid, p_days_old integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.archive_old_messages(days_old integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contact_filter_options(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_media_ids_for_analysis(p_user_id uuid, p_profile_id uuid, p_media_types text[], p_skip_analyzed boolean, p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_contact_method_access(p_contact_method_id uuid, p_access_type text, p_was_decrypted boolean, p_access_context text, p_ip_address inet) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_unread_alerts_count(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_auto_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.trigger_surveillance_alert_on_anomaly() FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_prompt_version_metrics() FROM anon;
REVOKE EXECUTE ON FUNCTION public.match_documents_v2(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid, p_profile_id uuid, p_source_types text[], p_date_from timestamp with time zone, p_date_to timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.keyword_search_documents(search_query text, p_user_id uuid, p_profile_id uuid, p_source_types text[], match_count integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.compute_profile_access_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_profile_access(p_profile_id uuid, p_access_type text, p_fields_accessed text[], p_was_decrypted boolean, p_access_context text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_message_for_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_media_for_analysis() FROM anon;
REVOKE EXECUTE ON FUNCTION public.match_documents(p_user_id uuid, p_query_embedding extensions.vector, p_match_threshold double precision, p_match_count integer, p_profile_id uuid, p_source_types text[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.queue_semantic_enrichment() FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_connection_path(p_user_id uuid, p_source_id uuid, p_target_id uuid, p_max_depth integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_shared_organizations(p_user_id uuid, p_profile_ids uuid[]) FROM anon;
REVOKE EXECUTE ON FUNCTION public.match_facial_embeddings(query_embedding extensions.vector, match_threshold double precision, match_count integer, p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.compute_psych_profile_access_hash() FROM anon;
REVOKE EXECUTE ON FUNCTION public.is_workspace_admin(ws_id uuid, uid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_contact_active_status(p_profile_id uuid, p_is_active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_bulk_session_stats() FROM anon;
REVOKE EXECUTE ON FUNCTION public.check_bulk_session_completion() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_account_storage_summary(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.increment_voice_session_progress(p_session_id uuid, p_is_completed boolean, p_is_failed boolean, p_is_skipped boolean, p_cost_cents integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_contacts_for_selection(p_user_id uuid, p_search_query text, p_recent_ids uuid[], p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.activate_contact_on_interaction() FROM anon;
REVOKE EXECUTE ON FUNCTION public.verify_audit_chain_segment(p_user_id uuid, p_start_date timestamp with time zone, p_end_date timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.log_security_event(p_event_type text, p_severity text, p_resource_type text, p_resource_id uuid, p_action_taken text, p_action_successful boolean, p_metadata jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.batch_merge_duplicates(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.claim_pending_tasks(p_session_id uuid, p_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.relink_email_threads_to_profiles(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.find_duplicate_profile(p_user_id uuid, p_first_name text, p_last_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.populate_cross_references() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_database_health_metrics(p_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.search_contacts_v5(p_user_id uuid, p_search_query text, p_relationship_type text, p_relationship_subtype text, p_tag text, p_is_favorite boolean, p_is_active boolean, p_first_letter text, p_sort_by text, p_sort_order text, p_limit integer, p_offset integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.merge_duplicate_profiles(p_primary_id uuid, p_duplicate_id uuid, p_user_id uuid) FROM anon;

-- 3. Replace USING(true) write policies with service_role-scoped policies
DROP POLICY IF EXISTS "Service role can insert audit logs" ON public.immutable_audit_logs;
CREATE POLICY "Service role can insert audit logs" ON public.immutable_audit_logs FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can insert access logs" ON public.sensitive_data_access_log;
CREATE POLICY "Service role can insert access logs" ON public.sensitive_data_access_log FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can insert detected items" ON public.detected_items;
CREATE POLICY "Service role can insert detected items" ON public.detected_items FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can insert unknown persons" ON public.unknown_persons;
CREATE POLICY "Service role can insert unknown persons" ON public.unknown_persons FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can insert extracted documents" ON public.extracted_documents;
CREATE POLICY "Service role can insert extracted documents" ON public.extracted_documents FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can update detected items" ON public.detected_items;
CREATE POLICY "Service role can update detected items" ON public.detected_items FOR UPDATE TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can update unknown persons" ON public.unknown_persons;
CREATE POLICY "Service role can update unknown persons" ON public.unknown_persons FOR UPDATE TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can update extracted documents" ON public.extracted_documents;
CREATE POLICY "Service role can update extracted documents" ON public.extracted_documents FOR UPDATE TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can update media" ON public.media;
CREATE POLICY "Service role can update media" ON public.media FOR UPDATE TO service_role USING (true) WITH CHECK (true);

-- 4. Lock down face-crops bucket (biometric PII) — owner-scoped only
DROP POLICY IF EXISTS "Public can view face crops" ON storage.objects;
UPDATE storage.buckets SET public = false WHERE id = 'face-crops';